version: "3.8"
services:
  #User-Profile-Service
  user-profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-profile-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/api/v2/spans
    links:
      - postgres-db
    ports:
      - '8080:8080'
    depends_on:
      - postgres-db
  #Postgres
  postgres-db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-db-data:/var/lib/postgres/data
  #pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - postgres-db
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  #zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_monitoring
    restart: always
    ports:
      - '9411:9411'
    depends_on:
      - user-profile-service