spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
  liquibase:
    change-log: file:db/db.changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

management:
  server:
    port: 8088
  endpoints:
    web:
      exposure:
        include: health, prometheus, liquibase
  # Show details of health endpoint
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  packagesToScan: com.iprody.userprofile.controller
  api-docs:
    path: /api/json
  swagger-ui:
    path: /api/ui.html
  show-actuator: true